apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config
  namespace: audiobookshelf
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: regional
  resources:
    requests:
      storage: 1Ti
  volumeName: audiobookshelf-config
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: metadata
  namespace: audiobookshelf
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: regional
  resources:
    requests:
      storage: 1Ti
  volumeName: audiobookshelf-metadata
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: library
  namespace: audiobookshelf
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: regional
  resources:
    requests:
      storage: 1Ti
  volumeName: audiobookshelf-library
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backup
  namespace: audiobookshelf
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: archive
  resources:
    requests:
      storage: 1Ti
  volumeName: audiobookshelf-backup