apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lib
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: regional
  resources:
    requests:
      storage: 1Ti
  volumeName: ntfy-lib
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cache
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: regional
  resources:
    requests:
      storage: 1Ti
  volumeName: ntfy-cache