apiVersion: k8s.mariadb.com/v1alpha1
kind: MaxScale
metadata:
  name: maxscale
  namespace: crm
  annotations:
        networking.gke.io/load-balancer-type: "Internal"
spec:
  # Connects to the MariaDB cluster defined above
  mariaDbRef:
    name: mariadb
  
  # Run 2 replicas for High Availability of the Proxy itself
  replicas: 2

  # This LoadBalancer IP is your single connection endpoint
  kubernetesService:
    type: LoadBalancer

  # Router: Automatically splits Reads and Writes
  # Port 3306 -> Writes go to Primary, Reads balanced to Replicas
  services:
    - name: rw-router
      router: readwritesplit
      listener:
        port: 3306
        protocol: MariaDBProtocol

  # Monitor: Handles Auto-Failover
  monitor:
    module: mariadbmon
    interval: 2s
    cooperativeMonitoring: majority_of_all
    params:
      auto_failover: "true"
      auto_rejoin: "true"
  
  resources:
    requests:
      cpu: 50m
      memory: 256Mi
    limits:
      memory: 256Mi