apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: gcp-secret-manager
  namespace: crm
spec:
  provider:
    gcpsm:
      projectID: au-crm-prod-485713
      auth:
        workloadIdentity:
          serviceAccountRef:
            name: secret-manager-secret-accessor
            namespace: crm