apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: database
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-manager
    kind: SecretStore
  target:
    name: database
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # Postgres connection string: postgres://<user>:<password>@<host>:<port>/<db>
        # Host is the service name of the Cloud SQL Proxy
        database-url: "postgres://windmill:{{ .database-password }}@cloud-sql-proxy.windmill.svc.cluster.local:5432/windmill?sslmode=disable"
  data:
    - secretKey: database-password
      remoteRef:
        key: DATABASE_PASSWORD