apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: gcp-secret-manager
spec:
  provider:
    gcpsm:
      projectID: au-windmill-prod-264762
      auth:
        workloadIdentity:
          serviceAccountRef:
            name: secret-manager-secret-accessor
