apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: password
  namespace: crm
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-manager
    kind: SecretStore
  target:
    name: password
    creationPolicy: Owner
  data:
    - secretKey: root-password
      remoteRef:
        key: ROOT_PASSWORD
    - secretKey: user-password
      remoteRef:
        key: USER_PASSWORD
    - secretKey: admin-password
      remoteRef:
        key: ADMIN_PASSWORD

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: access-key
  namespace: crm
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-manager
    kind: SecretStore
  target:
    name: access-key
    creationPolicy: Owner
  data:
    - secretKey: access-key-id
      remoteRef:
        key: ACCESS_KEY_ID
    - secretKey: secret-access-key
      remoteRef:
        key: SECRET_ACCESS_KEY