apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sites
  namespace: crm
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: regional
  resources:
    requests:
      storage: 1Ti # Must be <= the PV size
  volumeName: crm-sites # Explicitly binds to the PV created above