apiVersion: v1
kind: ServiceAccount
metadata:
  name: secret-manager-secret-accessor
  namespace: crm
  annotations:
    iam.gke.io/gcp-service-account: secret-manager-secret-accessor@au-crm-prod-485713.iam.gserviceaccount.com
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: storage-folder-admin
  namespace: crm
  annotations:
    iam.gke.io/gcp-service-account: storage-folder-admin@au-crm-prod-485713.iam.gserviceaccount.com
