apiVersion: batch/v1
kind: Job
metadata:
  name: chatwoot-migrate
spec:
  ttlSecondsAfterFinished: 300
  template:
    spec:
      containers:
        - name: db-migrate-job
          env:
            - name: REDIS_URL
              value: redis://valkey.chatwoot.asia-south1.prod.aurumor.com:6379
            - name: REDIS_PASSWORD
              value: ""
            - name: REDIS_PASSWORD
              value: ""