apiVersion: apps/v1
kind: Deployment
metadata:
  name: audiobookshelf
  namespace: audiobookshelf
spec:
  template:
    spec:
      containers:
      - name: audiobookshelf
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: 8080
          initialDelaySeconds: 30
          timeoutSeconds: 240
          periodSeconds: 240
          failureThreshold: 1
        readinessProbe:
          httpGet:
            path: /healthcheck
            port: 8080
          initialDelaySeconds: 30
          timeoutSeconds: 240
          periodSeconds: 240
          failureThreshold: 1
