apiVersion: v1
kind: ServiceAccount
metadata:
  name: secret-manager-secret-accessor
  annotations:
    iam.gke.io/gcp-service-account: secret-manager-secret-accessor@au-waha-prod-335035.iam.gserviceaccount.com