{{- if .Values.externalSecrets.enabled -}}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: password
  labels:
    {{- include "waha.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.storeName }}
    kind: SecretStore
  target:
    name: password
    creationPolicy: Owner
  data:
    - secretKey: database-password
      remoteRef:
        key: {{ .Values.externalSecrets.keys.databasePassword }}
    - secretKey: dashboard-password
      remoteRef:
        key: {{ .Values.externalSecrets.keys.dashboardPassword }}
    - secretKey: swagger-password
      remoteRef:
        key: {{ .Values.externalSecrets.keys.swaggerPassword }}

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: api
  labels:
    {{- include "waha.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.storeName }}
    kind: SecretStore
  target:
    name: api
    creationPolicy: Owner
  data:
    - secretKey: api-key
      remoteRef:
        key: {{ .Values.externalSecrets.keys.apiKey }}

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: access-key
  labels:
    {{- include "waha.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.storeName }}
    kind: SecretStore
  target:
    name: access-key
    creationPolicy: Owner
  data:
    - secretKey: access-key-id
      remoteRef:
        key: {{ .Values.externalSecrets.keys.accessKeyId }}
    - secretKey: secret-access-key
      remoteRef:
        key: {{ .Values.externalSecrets.keys.secretAccessKey }}
{{- end }}
