apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: password
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-manager
    kind: SecretStore
  target:
    name: password
    creationPolicy: Owner
  data:
    - secretKey: database-password
      remoteRef:
        key: DATABASE_PASSWORD
    - secretKey: dashboard-password
      remoteRef:
        key: WAHA_DASHBOARD_PASSWORD
    - secretKey: swagger-password
      remoteRef:
        key: WHATSAPP_SWAGGER_PASSWORD

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: api
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-manager
    kind: SecretStore
  target:
    name: api
    creationPolicy: Owner
  data:
    - secretKey: api-key
      remoteRef:
        key: WAHA_API_KEY

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: access-key
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-manager
    kind: SecretStore
  target:
    name: access-key
    creationPolicy: Owner
  data:
    - secretKey: access-key-id
      remoteRef:
        key: WAHA_S3_ACCESS_KEY_ID
    - secretKey: secret-access-key
      remoteRef:
        key: WAHA_S3_SECRET_ACCESS_KEY