apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: password
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-manager
    kind: SecretStore
  target:
    name: password
    creationPolicy: Owner
  data:
    - secretKey: database-password
      remoteRef:
        key: DATABASE_PASSWORD
    - secretKey: smtp-password
      remoteRef:
        key: SMTP_PASSWORD
        
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: credential
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-manager
    kind: SecretStore
  target:
    name: credential
    creationPolicy: Owner
  data:
    - secretKey: gcs-credentials
      remoteRef:
        key: GCS_CREDENTIALS

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: oauth
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-manager
    kind: SecretStore
  target:
    name: oauth
    creationPolicy: Owner
  data:
    - secretKey: google-oauth-client-id
      remoteRef:
        key: GOOGLE_OAUTH_CLIENT_ID
    - secretKey: google-oauth-client-secret
      remoteRef:
        key: GOOGLE_OAUTH_CLIENT_SECRET

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-manager
    kind: SecretStore
  target:
    name: secret
    creationPolicy: Owner
  data:
    - secretKey: secret-key-base
      remoteRef:
        key: SECRET_KEY_BASE