apiVersion: v1
kind: ServiceAccount
metadata:
  name: secrets-accessor
  namespace: n8n
  annotations:
    iam.gke.io/gcp-service-account: secrets-accessor@cb-n8n-prod-479922.iam.gserviceaccount.com
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloud-sql-client
  namespace: n8n
  annotations:
    iam.gke.io/gcp-service-account: cloud-sql-client@cb-n8n-prod-479922.iam.gserviceaccount.com