apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config
  namespace: komga
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: regional
  resources:
    requests:
      storage: 1Ti
  volumeName: komga-config
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data
  namespace: komga
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: regional
  resources:
    requests:
      storage: 1Ti
  volumeName: komga-data