apiVersion: v1
kind: PersistentVolume
metadata:
  name: komga-config
spec:
  capacity:
    storage: 1Ti
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: regional
  nfs:
    path: /share/komga/config
    server: filestore.komga.asia-south1.prod.aurumor.com
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: komga-data
spec:
  capacity:
    storage: 1Ti
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: regional
  nfs:
    path: /share/resources
    server: filestore.komga.asia-south1.prod.aurumor.com