apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: mariadb
  namespace: fcrm
  labels:
    app: fcrm
spec:
  replicas: 2

  maxScaleRef:
    name: maxscale

  timeZone: "Asia/Kolkata"

  replication:
    enabled: true
    primary:
      autoFailover: false 
    replica:
      syncTimeout: 10s
      maxLagSeconds: 10 

  resources:
    requests:
      cpu: 1000m
      memory: 2Gi
    limits:
      memory: 2Gi

  storage:
    size: 20Gi
    storageClassName: premium-rwo 
    resizeInUseVolumes: true

  rootPasswordSecretKeyRef:
    name: password
    key: root-password

  service:
    type: ClusterIP

  metrics:
    enabled: false