apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sites
  namespace: fcrm
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: regional
  resources:
    requests:
      storage: 1Ti # Must be <= the PV size
  volumeName: fcrm-sites # Explicitly binds to the PV created above