apiVersion: v1
kind: PersistentVolume
metadata:
  name: fcrm-sites
  namespace: fcrm
spec:
  capacity:
    storage: 1Ti # Update this to match your Filestore size
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: regional
  nfs:
    path: /share/fcrm/sites
    server: filestore.fcrm.asia-south1.prod.aurumor.com