apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: gcp-secret-manager
  namespace: fcrm
spec:
  provider:
    gcpsm:
      projectID: cb-fcrm-prod-t3ys4g
      auth:
        workloadIdentity:
          serviceAccountRef:
            name: secrets-accessor
            namespace: fcrm