apiVersion: v1
kind: ServiceAccount
metadata:
  name: secrets-accessor
  namespace: fcrm
  annotations:
    iam.gke.io/gcp-service-account: secrets-accessor@cb-fcrm-prod-t3ys4g.iam.gserviceaccount.com