apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Sets the namespace for all resources (except cluster-wide ones like PVs)
namespace: erpnext

# 1. Include all your infrastructure and database manifests
resources:
  - namespace.yaml
  - service-account.yaml
  - secret-store.yaml
  - external-secret.yaml
  - persistent-volume.yaml
  - persistent-volume-claim.yaml
  - mariadb.yaml
  - vertical-pod-autoscaler.yaml
  - maxscale.yaml
  - user.yaml
  - grant.yaml
  - backup.yaml
  - configmap.yaml
  - cronjobs.yaml

# 2. Integrate the erpnext Helm Chart
helmCharts:
  - name: erpnext
    repo: https://helm.erpnext.com
    releaseName: erpnext
    namespace: erpnext
    version: 8.0.19
    valuesFile: values.yaml
    includeCRDs: true

# 3. Patch the Service to add the NEG Annotation (replaces your manual kubectl annotate)
patches:
  - path: patches/service-nginx.yaml
    target:
      kind: Service
      name: erpnext
  - target:
      kind: Pod
      name: erpnext-test-connection
    patch: |-
      apiVersion: v1
      kind: Pod
      metadata:
        name: erpnext-test-connection
      $patch: delete