apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sites
  namespace: erpnext
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: regional
  resources:
    requests:
      storage: 1Ti # Must be <= the PV size
  volumeName: erpnext-sites # Explicitly binds to the PV created above
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backup
  namespace: erpnext
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: archive
  resources:
    requests:
      storage: 1Ti
  volumeName: erpnext-backup
