apiVersion: v1
kind: Service
metadata:
  namespace: stalwart
  name: stalwart
  labels:
    app: stalwart
  annotations:
    cloud.google.com/neg: '{"exposed_ports": {"8080":{}}}'
spec:
  type: ClusterIP
  selector:
    app: stalwart
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
    - port: 443
      targetPort: 443
      protocol: TCP
      name: https
    - port: 25
      targetPort: 25
      protocol: TCP
      name: smtp
    - port: 587
      targetPort: 587
      protocol: TCP
      name: submission
    - port: 465
      targetPort: 465
      protocol: TCP
      name: smtps
    - port: 143
      targetPort: 143
      protocol: TCP
      name: imap
    - port: 993
      targetPort: 993
      protocol: TCP
      name: imaps
    - port: 4190
      targetPort: 4190
      protocol: TCP
      name: sieve
    - port: 110
      targetPort: 110
      protocol: TCP
      name: pop3
    - port: 995
      targetPort: 995
      protocol: TCP
      name: pop3s
