apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: gcp-secret-manager
spec:
  provider:
    gcpsm:
      projectID: au-dify-prod-364229
      auth:
        workloadIdentity:
          serviceAccountRef:
            name: secret-manager-secret-accessor
