apiVersion: v1
kind: ServiceAccount
metadata:
  name: secret-manager-secret-accessor
  annotations:
    iam.gke.io/gcp-service-account: secret-manager-secret-accessor@au-dify-prod-364229.iam.gserviceaccount.com

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloud-sql-client
  annotations:
    iam.gke.io/gcp-service-account: cloud-sql-client@au-dify-prod-364229.iam.gserviceaccount.com