apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: key
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-manager
    kind: SecretStore
  target:
    name: key
    creationPolicy: Owner
  data:
    - secretKey: n8n-encryption-key
      remoteRef:
        key: N8N_ENCRYPTION_KEY

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: password
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-manager
    kind: SecretStore
  target:
    name: password
    creationPolicy: Owner
  data:
    - secretKey: db-postgresdb-password
      remoteRef:
        key: DB_POSTGRESDB_PASSWORD

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: license
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-manager
    kind: SecretStore
  target:
    name: license
    creationPolicy: Owner
  data:
    - secretKey: n8n-license-activation-key
      remoteRef:
        key: N8N_LICENSE_ACTIVATION_KEY

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: access-key
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-manager
    kind: SecretStore
  target:
    name: access-key
    creationPolicy: Owner
  data:
    - secretKey: n8n-external-storage-s3-access-key
      remoteRef:
        key: N8N_EXTERNAL_STORAGE_S3_ACCESS_KEY
    - secretKey: n8n-external-storage-s3-access-secret
      remoteRef:
        key: N8N_EXTERNAL_STORAGE_S3_ACCESS_SECRET

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: auth-token
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-manager
    kind: SecretStore
  target:
    name: auth-token
    creationPolicy: Owner
  data:
    - secretKey: n8n-runners-auth-token
      remoteRef:
        key: N8N_RUNNERS_AUTH_TOKEN