apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: gcp-secret-manager
  namespace: n8n
spec:
  provider:
    gcpsm:
      projectID: cb-n8n-prod-479922
      auth:
        workloadIdentity:
          serviceAccountRef:
            name: secrets-accessor
            namespace: n8n