apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: password
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-manager
    kind: SecretStore
  target:
    name: password
    creationPolicy: Owner
  data:
    - secretKey: convoy-db-password
      remoteRef:
        key: CONVOY_DB_PASSWORD

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: license-key
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-manager
    kind: SecretStore
  target:
    name: license-key
    creationPolicy: Owner
  data:
    - secretKey: convoy-license-key
      remoteRef:
        key: CONVOY_LICENSE_KEY