apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config
  namespace: stalwart
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: regional
  resources:
    requests:
      storage: 1Ti
  volumeName: stalwart-config