apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: gcp-secret-manager
  namespace: erpnext
spec:
  provider:
    gcpsm:
      projectID: au-erpnext-prod-485714
      auth:
        workloadIdentity:
          serviceAccountRef:
            name: secret-manager-secret-accessor
            namespace: erpnext