apiVersion: v1
kind: ServiceAccount
metadata:
  name: secret-manager-secret-accessor
  namespace: erpnext
  annotations:
    iam.gke.io/gcp-service-account: secret-manager-secret-accessor@au-erpnext-prod-485714.iam.gserviceaccount.com
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: storage-folder-admin
  namespace: erpnext
  annotations:
    iam.gke.io/gcp-service-account: storage-folder-admin@au-erpnext-prod-485714.iam.gserviceaccount.com
