apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: mariadb
  namespace: erpnext
spec:
  targetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: mariadb
  updatePolicy:
    updateMode: "Auto"
