apiVersion: v1
kind: ServiceAccount
metadata:
  # The name of your Kubernetes Service Account
  name: storage-folder-admin
  namespace: erpnext
  annotations:
    iam.gke.io/gcp-service-account: storage-folder-admin@{PROJECT_NAME}.iam.gserviceaccount.com