apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: audiobookshelf-vpa
  namespace: audiobookshelf
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: audiobookshelf
  updatePolicy:
    updateMode: Off
  resourcePolicy:
    containerPolicies:
    - containerName: '*'
      minAllowed:
        cpu: 50m
        memory: 52Mi
      controlledResources:
      - cpu
      - memory
