apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: komga
  name: komga
  labels:
    app: komga
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: komga
  template:
    metadata:
      labels:
        app: komga
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: komga
          image: gotson/komga
          ports:
            - containerPort: 80
              name: http
          env:
            - name: TZ
              value: "Asia/Kolkata"
          resources:
            requests:
              cpu: 500m
              memory: 500Mi
            limits:
              cpu: 1000m
              memory: 1Gi
          volumeMounts:
            - name: config
              mountPath: /config
            - name: data
              mountPath: /data
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: config
        - name: data
          persistentVolumeClaim:
            claimName: data
