apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: database
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-manager
    kind: SecretStore
  target:
    name: database
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        coder-pg-connection-url: "postgres://coder:{{ .password }}@cloud-sql-proxy.coder.svc.cluster.local:5432/coder?sslmode=disable"
  data:
    - secretKey: password
      remoteRef:
        key: DATABASE_PASSWORD