apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: cloud-sql-proxy-vpa
  namespace: windmill
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cloud-sql-proxy
  updatePolicy:
    updateMode: Off
  resourcePolicy:
    containerPolicies:
    - containerName: '*'
      minAllowed:
        cpu: 50m
        memory: 52Mi
      controlledResources:
      - cpu
      - memory
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: windmill-extra-vpa
  namespace: windmill
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: windmill-extra
  updatePolicy:
    updateMode: Off
  resourcePolicy:
    containerPolicies:
    - containerName: '*'
      minAllowed:
        cpu: 50m
        memory: 52Mi
      controlledResources:
      - cpu
      - memory
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: windmill-workers-browser-vpa
  namespace: windmill
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: windmill-workers-browser
  updatePolicy:
    updateMode: Off
  resourcePolicy:
    containerPolicies:
    - containerName: '*'
      minAllowed:
        cpu: 50m
        memory: 52Mi
      controlledResources:
      - cpu
      - memory
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: windmill-workers-default-vpa
  namespace: windmill
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: windmill-workers-default
  updatePolicy:
    updateMode: Off
  resourcePolicy:
    containerPolicies:
    - containerName: '*'
      minAllowed:
        cpu: 50m
        memory: 52Mi
      controlledResources:
      - cpu
      - memory
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: windmill-workers-media-vpa
  namespace: windmill
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: windmill-workers-media
  updatePolicy:
    updateMode: Off
  resourcePolicy:
    containerPolicies:
    - containerName: '*'
      minAllowed:
        cpu: 50m
        memory: 52Mi
      controlledResources:
      - cpu
      - memory
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: windmill-workers-native-vpa
  namespace: windmill
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: windmill-workers-native
  updatePolicy:
    updateMode: Off
  resourcePolicy:
    containerPolicies:
    - containerName: '*'
      minAllowed:
        cpu: 50m
        memory: 52Mi
      controlledResources:
      - cpu
      - memory
