apiVersion: v1
kind: PersistentVolume
metadata:
  name: portainer-data
spec:
  capacity:
    storage: 1Ti
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: regional
  nfs:
    path: /share/portainer/data
    server: filestore.portainer.asia-south1.prod.aurumor.com